sudo: require
services:
  - docker

before_install:
  - docker build -t sabyasachig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sabyasachig/docker-react npm run test -- --coverage
